default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40284_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40284_test

production:
  <<: *default
  adapter: mysql2
  database: furima-40284_production
  username: root
  password: <%= ENV['mesqueunCLUB6810'] %>
  socket: /var/lib/mysql/mysql.sock